"""initial schema

Revision ID: e436ad52e8f4
Revises: 
Create Date: 2026-07-24 18:53:26.359988

"""
from datetime import date
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.partitioning import ensure_partitions_for_range


# revision identifiers, used by Alembic.
revision: str = 'e436ad52e8f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _add_months(d: date, months: int) -> date:
    month = d.month - 1 + months
    year = d.year + month // 12
    return date(year, month % 12 + 1, 1)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_code'), 'data_sources', ['code'], unique=True)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('listed_date', sa.Date(), nullable=True),
    sa.Column('delisted_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_type in ('equity','etf','index','future','other')", name='ck_symbol_asset_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', name='uq_symbol_ticker')
    )
    op.create_index(op.f('ix_symbols_ticker'), 'symbols', ['ticker'], unique=False)
    op.create_table('option_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying_symbol_id', sa.Integer(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("option_type in ('call','put')", name='ck_option_contract_type'),
    sa.ForeignKeyConstraint(['underlying_symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('underlying_symbol_id', 'expiration', 'strike', 'option_type', name='uq_option_contract')
    )
    op.create_index(op.f('ix_option_contracts_expiration'), 'option_contracts', ['expiration'], unique=False)
    op.create_index(op.f('ix_option_contracts_underlying_symbol_id'), 'option_contracts', ['underlying_symbol_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('bar_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'source_id', 'interval', 'bar_time', name='uq_price_bar')
    )
    op.create_index('ix_price_history_symbol_time', 'price_history', ['symbol_id', 'interval', 'bar_time'], unique=False)
    op.create_table('stock_ticks',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('tick_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tick_type', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('bid', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ask', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exchange', sa.String(length=16), nullable=True),
    sa.Column('conditions', sa.String(length=64), nullable=True),
    sa.CheckConstraint("tick_type in ('trade','quote')", name='ck_stock_tick_type'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id', 'tick_time'),
    postgresql_partition_by='RANGE (tick_time)'
    )
    op.create_index('ix_stock_ticks_symbol_time', 'stock_ticks', ['symbol_id', 'tick_time'], unique=False)
    op.create_index('ix_stock_ticks_time_brin', 'stock_ticks', ['tick_time'], unique=False, postgresql_using='brin')
    op.create_table('symbol_source_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_symbol', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_symbol', name='uq_symbol_source_symbol'),
    sa.UniqueConstraint('symbol_id', 'source_id', name='uq_symbol_source_once')
    )
    op.create_index(op.f('ix_symbol_source_map_source_id'), 'symbol_source_map', ['source_id'], unique=False)
    op.create_index(op.f('ix_symbol_source_map_symbol_id'), 'symbol_source_map', ['symbol_id'], unique=False)
    op.create_table('option_contract_source_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_contract_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_symbol', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['option_contract_id'], ['option_contracts.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_contract_id', 'source_id', name='uq_option_contract_source_once'),
    sa.UniqueConstraint('source_id', 'source_symbol', name='uq_option_contract_source_symbol')
    )
    op.create_index(op.f('ix_option_contract_source_map_option_contract_id'), 'option_contract_source_map', ['option_contract_id'], unique=False)
    op.create_index(op.f('ix_option_contract_source_map_source_id'), 'option_contract_source_map', ['source_id'], unique=False)
    op.create_table('option_quotes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('option_contract_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('quote_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bid', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ask', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('open_interest', sa.BigInteger(), nullable=True),
    sa.Column('implied_volatility', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('delta', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('gamma', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('theta', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('vega', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('rho', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['option_contract_id'], ['option_contracts.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id', 'quote_time'),
    sa.UniqueConstraint('option_contract_id', 'source_id', 'quote_time', name='uq_option_quote'),
    postgresql_partition_by='RANGE (quote_time)'
    )
    op.create_index('ix_option_quotes_contract_time', 'option_quotes', ['option_contract_id', 'quote_time'], unique=False)
    op.create_table('option_ticks',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('option_contract_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('tick_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tick_type', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('bid', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ask', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exchange', sa.String(length=16), nullable=True),
    sa.Column('conditions', sa.String(length=64), nullable=True),
    sa.CheckConstraint("tick_type in ('trade','quote')", name='ck_option_tick_type'),
    sa.ForeignKeyConstraint(['option_contract_id'], ['option_contracts.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id', 'tick_time'),
    postgresql_partition_by='RANGE (tick_time)'
    )
    op.create_index('ix_option_ticks_contract_time', 'option_ticks', ['option_contract_id', 'tick_time'], unique=False)
    op.create_index('ix_option_ticks_time_brin', 'option_ticks', ['tick_time'], unique=False, postgresql_using='brin')
    # ### end Alembic commands ###

    # Pre-create a rolling window of monthly partitions (last month through 3 months out) for
    # the partitioned tables, so ingestion works immediately after migrating. The ingestion
    # services also call ensure_partition() before each insert as a safety net for dates
    # outside this window - see app/partitioning.py.
    bind = op.get_bind()
    today = date.today()
    start = _add_months(today, -1)
    end = _add_months(today, 3)
    for table in ("option_quotes", "stock_ticks", "option_ticks"):
        ensure_partitions_for_range(bind, table, start, end)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_option_ticks_time_brin', table_name='option_ticks', postgresql_using='brin')
    op.drop_index('ix_option_ticks_contract_time', table_name='option_ticks')
    op.drop_table('option_ticks')
    op.drop_index('ix_option_quotes_contract_time', table_name='option_quotes')
    op.drop_table('option_quotes')
    op.drop_index(op.f('ix_option_contract_source_map_source_id'), table_name='option_contract_source_map')
    op.drop_index(op.f('ix_option_contract_source_map_option_contract_id'), table_name='option_contract_source_map')
    op.drop_table('option_contract_source_map')
    op.drop_index(op.f('ix_symbol_source_map_symbol_id'), table_name='symbol_source_map')
    op.drop_index(op.f('ix_symbol_source_map_source_id'), table_name='symbol_source_map')
    op.drop_table('symbol_source_map')
    op.drop_index('ix_stock_ticks_time_brin', table_name='stock_ticks', postgresql_using='brin')
    op.drop_index('ix_stock_ticks_symbol_time', table_name='stock_ticks')
    op.drop_table('stock_ticks')
    op.drop_index('ix_price_history_symbol_time', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_option_contracts_underlying_symbol_id'), table_name='option_contracts')
    op.drop_index(op.f('ix_option_contracts_expiration'), table_name='option_contracts')
    op.drop_table('option_contracts')
    op.drop_index(op.f('ix_symbols_ticker'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_data_sources_code'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_table('companies')
    # ### end Alembic commands ###
